export function menloInterview(): string {
  return `<section class="ml-interview" id="conversation" aria-labelledby="conversation-title">
<header class="ml-interview-heading"><p class="ml-interview-eyebrow">An imagined conversation</p><h2 id="conversation-title">Does this deserve to exist?</h2><p>A skeptical interviewer. Menlo’s case for what it could bring to the world.</p></header>
<dl class="ml-interview-transcript">
<div class="ml-interview-exchange"><dt><span class="ml-interview-speaker">Interviewer</span>What are you actually trying to change?</dt><dd><span class="ml-interview-speaker">Menlo</span>An app sitting in a repository cannot tell you whether somebody needs it. We want more small, unfinished, personal ideas to reach people who will actually try them. Menlo turns a public GitHub app into a link you can share. The point is to learn something from the person on the other end.</dd></div>
<div class="ml-interview-exchange"><dt><span class="ml-interview-speaker">Interviewer</span>A link is easy. Getting somebody to care is hard.</dt><dd><span class="ml-interview-speaker">Menlo</span>Yes. A listing does not guarantee users or honest feedback. Start with someone whose problem you understand. Invite them to try the app. Watch where they get stuck. Ask what they would change. Menlo can help you share the software; you still have to earn their attention.</dd></div>
<div class="ml-interview-exchange"><dt><span class="ml-interview-speaker">Interviewer</span>“Bypass the app stores.” What’s the catch?</dt><dd><span class="ml-interview-speaker">Menlo</span>Today, the person trying an app needs a Mac, Xcode, an Apple Account, and their iPhone. They review the source and approve a local build, signed with their own Apple identity. That is a lot to ask. This is an early path for people willing to go through that setup. Making the handoff easier is work we still have to do.</dd></div>
<div class="ml-interview-exchange"><dt><span class="ml-interview-speaker">Interviewer</span>And there’s a coin. Does the product need it?</dt><dd><span class="ml-interview-speaker">Menlo</span>Sharing and trying apps do not require a coin. We plan to launch one on Base through Clanker. It has not launched, and there is no contract address yet. The product has to earn its place through actual use.</dd></div>
<div class="ml-interview-exchange"><dt><span class="ml-interview-speaker">Interviewer</span>What would convince me this matters?</dt><dd><span class="ml-interview-speaker">Menlo</span>A builder shares an app. Another person gets it running, uses it, and gives feedback specific enough to change what gets built next. Then they come back for the update. If Menlo helps that happen, more people get a say in the software they use. That is the loop we need to prove.</dd></div>
</dl></section>`;
}
