/** MENLO's GitHub-first front door (ADR 0040). */
export function menloHome(apps: string, activity: string, status: string): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>MENLO — From GitHub to their iPhone</title>
<meta name="description" content="Deploy your iOS app from GitHub. Share a link. Let someone build it on their Mac, try it on their iPhone, and give practical feedback.">
<meta name="theme-color" content="#f6f3ea"><meta property="og:title" content="Menlo — Your app. In someone else’s hands."><meta property="og:description" content="Deploy from GitHub. Share a link. Get hands-on feedback."><meta property="og:image" content="https://tohseno.com/menlo/hero-sharing.png?v=1">
<link rel="canonical" href="https://tohseno.com/"><link rel="icon" href="/menlo/favicon.svg?v=1" type="image/svg+xml">
<link rel="preload" href="/menlo/hero-sharing.png?v=1" as="image"><link rel="stylesheet" href="/menlo/tokens.css?v=1"><link rel="stylesheet" href="/menlo/home.css?v=2">
<script src="/menlo/home.js?v=2" defer></script></head>
<body class="menlo-landing"><a class="ml-skip" href="#main">Skip to content</a>
<header class="ml-container ml-header"><a class="ml-wordmark" href="/" aria-label="Menlo home"><img src="/menlo/menlo-mark.svg?v=1" width="40" height="40" alt="">menlo</a><nav aria-label="Primary"><a class="ml-desktop-link" href="#how-it-works">How it works</a><a href="/apps">Explore apps</a><a class="ml-button ml-desktop-link" href="#install">Deploy your app</a></nav></header>
<main id="main"><section class="ml-container ml-hero"><div><p class="ml-eyebrow">iOS APPS. REAL PEOPLE. REAL FEEDBACK.</p><h1 class="ml-display ml-h1">Your GitHub app.<br>On their iPhone.</h1><p class="ml-body">Waiting to get your app into someone’s hands? Deploy it on MENLO. Share a link, let them try it on their own iPhone, and get feedback you can build on.</p>
<div id="install"><p class="ml-install-label">GitHub preview · from your app’s repository</p><div class="ml-command"><pre class="ml-code" id="install-command">npm i -g https://github.com/jpfraneto/tohseno/releases/download/v1.3.0-rc.1/tohseno-1.3.0.tgz\ntohseno deploy</pre><button id="copy-command" aria-label="Copy deploy commands">Copy commands</button></div><p id="copy-status" role="status" aria-live="polite"></p><p class="ml-small ml-muted">Preview CLI 1.3.0. The normal npm i -g tohseno command switches to this workflow after npm publication. Get tohseno.com/your-app; menlo deploy works too.</p></div>
<p class="ml-small">Public GitHub repositories first. Testers need a Mac, Xcode, their own Apple signing identity, and a paired iPhone.</p><div class="ml-links"><a href="/apps">Explore apps ↗</a><a href="/download/macos">Mac download &amp; release status</a></div></div>
<img class="ml-hero-art" src="/menlo/hero-sharing.png?v=1" width="1536" height="1024" alt="" fetchpriority="high"></section>
<section class="ml-container ml-section" id="how-it-works"><p class="ml-eyebrow">KEEP YOUR WORKFLOW. SHARE THE RESULT.</p><h2 class="ml-display ml-h2">One deploy. A living app.</h2><ol class="ml-steps"><li><span class="ml-number">01</span><h3>Connect GitHub</h3><p>Commit and push your iOS project. Run tohseno deploy. Sign in with GitHub, or use your existing GitHub CLI session.</p></li><li><span class="ml-number">02</span><h3>Share the link</h3><p>Your tester opens the link in MENLO, reviews the source, and builds on their own Mac. Their Apple identity signs the app for their intended iPhone.</p></li><li><span class="ml-number">03</span><h3>Push. Try. Improve.</h3><p>Keep committing as usual. Their Mac checks GitHub and Companion shows how many commits their installed app is behind. They choose Update; their Mac prepares the next build.</p></li></ol><p class="ml-note">No source upload to MENLO. No gas or wallet. Apple’s pairing, signing, and provisioning limits still apply. Build scripts can require review on the tester’s Mac.</p></section>
<section class="ml-container ml-section" id="apps"><div class="ml-section-heading"><h2 class="ml-display ml-h2">Ready for another pair of hands.</h2><a href="/apps">Explore all apps ↗</a></div><div class="ml-app-grid">${apps}</div><p class="ml-small ml-muted">${status}</p></section>
<section class="ml-container ml-section" id="roadmap"><p class="ml-eyebrow">THE ROADMAP, STRAIGHT UP</p><h2 class="ml-display ml-h2">Make it useful. Then decentralize.</h2><ol class="ml-steps"><li><span class="ml-number">NOW</span><h3>GitHub + a small directory</h3><p>GitHub is your identity and source of truth. MENLO operates a centralized app directory with an off-chain ledger. Source travels from GitHub to the tester’s Mac.</p></li><li><span class="ml-number">NEXT</span><h3>Learn from real installs</h3><p>Make signing, updates, and feedback easier by watching real people use them. Public repositories and foreground Companion updates come first.</p></li><li><span class="ml-number">LATER</span><h3>Decentralize when it helps</h3><p>On-chain witnessing can return in v1 or v2 when it earns its cost. Today, contracts and gas are outside the normal deploy-and-try flow.</p></li></ol></section>
${activity ? `<section class="ml-container ml-section"><h2>Historical Registry activity</h2><p>Recipients build and sign it on their Mac.</p>${activity}</section>` : ""}<section class="ml-container ml-belief"><img src="/menlo/spectrum-rule.svg?v=1" width="96" height="8" alt=""><h2 class="ml-display ml-h2">“Deploy it on MENLO.<br>I’ll try it right now.”</h2><p class="ml-body">A working app is a better conversation starter than another screenshot.</p><a class="ml-button" href="#install">Start sharing</a></section></main>
<footer class="ml-container ml-footer"><div><span class="ml-wordmark">menlo</span><p>A network for app makers.</p><p class="ml-small ml-muted">GitHub identity. Local builds. Human feedback.</p></div><nav aria-label="Footer"><a href="#roadmap">Roadmap</a><a href="/registry">Historical Registry</a><a href="#how-it-works">How it works</a><a href="https://github.com/jpfraneto/tohseno">GitHub</a><a href="/docs">Documentation</a><a href="/privacy">Privacy</a></nav></footer></body></html>`;
}
